version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - "./:/usr/src/app/"
  db:
    image: mysql:latest
    cap_add:
      - SYS_NICE
    env_file:
      - .env
    ports:
      - "50101:3306"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "-u${MYSQL_USER:-root}",
          "-p${MYSQL_PASSWORD:-root}",
          "ping",
        ]
      timeout: 20s
      retries: 3
    restart: always
